//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public Children()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public string Name { get; set; }
        public string Sex { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
