//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Schedule = new HashSet<Schedule>();
            this.Children = new HashSet<Children>();
        }
    
        public int PersonnelNumber { get; set; }
        public string FullName { get; set; }
        public string PassportData { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Sex { get; set; }
        public string Position { get; set; }
        public string AmountOfChildren { get; set; }
    
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual ICollection<Children> Children { get; set; }
    }
}
